CREATE TABLE users (
    id bigint generated by default as identity,
    nickname varchar(64) not null,
    email varchar(128) not null,
    password varchar(128) not null,

    primary key (id),
    unique (nickname),
    unique (email)
);

CREATE TABLE musics(
    id bigint generated by default as identity,
    original_name varchar(128) null,
    store_name varchar(64) null,
    singer varchar(32) null,
    play_time bigint null,
    create_time timestamp not null default current_timestamp,

    primary key (id)
)