CREATE TABLE users (
    id bigint generated by default as identity,
    nickname varchar(64) not null,
    email varchar(128) not null,
    password varchar(128) not null,

    primary key (id),
    unique (nickname)
);

CREATE INDEX idx_email ON users (email);

CREATE TABLE musics(
    id bigint generated by default as identity,
    name varchar(100) not null,
    store_name varchar(64) null,
    singer varchar(20) not null,
    play_time int null,
    create_time timestamp not null,

    primary key (id)
);

CREATE INDEX idx_name ON musics (name);
CREATE INDEX idx_singer ON musics (singer);